### ISSUE TITLE
Small fix to compile on Mac OS X

### ISSUE THREAD

**Issue by santiontanon** [ralferoo/cpctools#2]
the provided sourcecode for cdt2 does not compile out of the box on a Mac. But all is needed is to replace line 27 in 2cdt.c from this:

#include <sys/io.h>

to this:

#ifdef __APPLE__
        #include <sys/uio.h>
#else
        #include <sys/io.h>
#endif

And then it all compiles fine :)

**Comment by ralferoo** [comment]
Fixed in 650bbd2ed9d930f1163f4c3af7e1c95746f12095

**Comment by ralferoo** [comment]
Thanks for the report! :)

**Comment by santiontanon** [comment]
No problem! Thanks for the tools! :D
